"""empty message

Revision ID: 840dc99858ef
Revises: eb90a4e463e0
Create Date: 2020-06-11 02:08:40.389921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840dc99858ef'
down_revision = 'eb90a4e463e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slide_show_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_show_images',
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###
