"""empty message

Revision ID: d4df38b943d5
Revises: 840dc99858ef
Create Date: 2020-06-12 00:24:10.262420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4df38b943d5'
down_revision = '840dc99858ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'home_categories_order', ['order'])
    op.create_unique_constraint(None, 'home_slide_show_images', ['order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_slide_show_images', type_='unique')
    op.drop_constraint(None, 'home_categories_order', type_='unique')
    # ### end Alembic commands ###
